import { CONFIG_FILE } from '../constants.js';
import type { ForgeLoopManifest } from '../types.js';
import type { FileSpec } from '../utils/fs.js';
import {
	packageManagerCliCommand,
	packageManagerField,
	packageManagerInstallCommand,
	packageManagerScriptCommand,
} from '../utils/package-manager.js';
import {
	applyPrismaPackageJson,
	databaseFiles,
	prismaFiles,
} from './project-database.js';
import { ciFiles, dockerFiles } from './project-ops.js';
import {
	biomeConfig,
	eslintConfig,
	prettierConfig,
	tsconfig,
} from './project-tooling.js';
import {
	hasHandlers,
	renderEntryFile,
	renderInitialHandlerFiles,
	renderStarterRuntimeFiles,
} from './runtime.js';
import { RenderProjectFilesOptions, fileExtension } from './shared.js';

function generatedReadme(manifest: ForgeLoopManifest) {
	const handlerProject = hasHandlers(manifest);
	const setupLines = [
		`1. Install dependencies with \`${packageManagerInstallCommand(manifest.packageManager)}\`.`,
		'2. Rename `.env.example` to `.env`.',
		manifest.features.database
			? '3. Fill in your Discord credentials and `DATABASE_URL` in `.env`.'
			: '3. Fill in your Discord credentials in `.env`.',
	];

	if (manifest.features.database?.orm === 'prisma') {
		setupLines.push(
			`4. Generate the Prisma client and push the schema with \`${packageManagerScriptCommand(manifest.packageManager, 'db:push')}\`.`,
			`5. Start the bot with \`${packageManagerScriptCommand(manifest.packageManager, 'dev')}\`.`,
		);
	} else {
		setupLines.push(
			`4. Start the bot with \`${packageManagerScriptCommand(manifest.packageManager, 'dev')}\`.`,
		);
	}

	return `# ${manifest.projectName}

Generated by ForgeLoop.

Project shape: ${manifest.preset}

## Setup

${setupLines.join('\n')}

## ForgeLoop

\`\`\`bash
${packageManagerCliCommand(
	manifest.packageManager,
	handlerProject ? 'add command status' : 'info',
)}
\`\`\`
${handlerProject ? `\n## Command Sync\n\nCommands sync automatically on startup.\n\n- Development defaults to guild sync and requires \`GUILD_ID\`\n- Production defaults to global sync when \`NODE_ENV=production\`\n- Manual deploy: \`${packageManagerCliCommand(manifest.packageManager, 'deploy commands --guild')}\` (or \`--global\` for global commands)\n` : ''}

## Managed by ForgeLoop

This project includes \`${CONFIG_FILE}\` and is expected to be maintained with ForgeLoop commands.
`;
}

function projectConfig(manifest: ForgeLoopManifest) {
	return `let defineConfig = (config) => config;

try {
  ({ defineConfig } = await import('create-forgeloop/config'));
} catch {
  // Keep the generated config usable before dependencies are installed.
}

export default defineConfig(${JSON.stringify(manifest, null, 2)});
`;
}

function packageJson(
	manifest: ForgeLoopManifest,
	options: Required<RenderProjectFilesOptions>,
) {
	const isTs = manifest.language === 'ts';
	const mainFile = `src/index.${fileExtension(manifest.language)}`;
	const scripts: Record<string, string> = {
		dev: isTs ? `tsx ${mainFile}` : `node ${mainFile}`,
		start: isTs ? `node --import tsx ${mainFile}` : `node ${mainFile}`,
	};
	const dependencies: Record<string, string> = {
		'discord.js': '^14.26.2',
		dotenv: '^17.2.3',
	};
	const devDependencies: Record<string, string> = isTs
		? {
				[options.cliPackageName]: options.cliPackageVersion,
				'@types/node': '^24.7.2',
				tsx: '^4.20.6',
				typescript: '^5.9.3',
			}
		: {
				[options.cliPackageName]: options.cliPackageVersion,
			};

	if (isTs) {
		scripts.typecheck = 'tsc --noEmit';
		scripts.build = 'tsc';
	}

	if (manifest.features.tooling === 'eslint-prettier') {
		scripts.lint = 'eslint .';
		scripts.format = 'prettier --write .';
		Object.assign(devDependencies, {
			eslint: '^9.38.0',
			globals: '^16.4.0',
			prettier: '^3.6.2',
		});
		if (isTs) {
			Object.assign(devDependencies, {
				'typescript-eslint': '^8.46.2',
			});
		}
	}

	if (manifest.features.tooling === 'biome') {
		scripts.lint = 'biome check .';
		scripts.format = 'biome format --write .';
		Object.assign(devDependencies, {
			'@biomejs/biome': '^1.9.4',
		});
	}

	applyPrismaPackageJson(manifest, dependencies, devDependencies, scripts);

	return JSON.stringify(
		{
			name: manifest.projectName,
			version: '0.1.0',
			private: true,
			type: 'module',
			packageManager: packageManagerField(manifest.packageManager),
			scripts,
			dependencies,
			devDependencies:
				Object.keys(devDependencies).length > 0 ? devDependencies : undefined,
		},
		null,
		2,
	);
}


function envExample(manifest: ForgeLoopManifest) {
	const lines = [
		'DISCORD_TOKEN=replace-me',
		'CLIENT_ID=replace-me',
		'GUILD_ID=replace-me',
	];
	if (manifest.features.database?.provider === 'sqlite') {
		lines.push('DATABASE_URL="file:./dev.db"');
	}
	if (manifest.features.database?.provider === 'postgresql') {
		lines.push(
			'DATABASE_URL="postgresql://user:password@localhost:5432/forgeloop"',
		);
	}

	return `${lines.join('\n')}\n`;
}

function envConfig(language: ForgeLoopManifest['language']) {
	return `export function assertRequiredEnv(key${language === 'ts' ? ': string' : ''})${language === 'ts' ? ': string' : ''} {
  const value = process.env[key];
  if (!value) {
    throw new Error(\`Missing required environment variable: \${key}\`);
  }

  return value;
}
`;
}

export function buildProjectFiles(
	manifest: ForgeLoopManifest,
	options: RenderProjectFilesOptions = {},
): FileSpec[] {
	const extension = fileExtension(manifest.language);
	const resolvedOptions: Required<RenderProjectFilesOptions> = {
		cliPackageName: options.cliPackageName ?? 'create-forgeloop',
		cliPackageVersion: options.cliPackageVersion ?? 'latest',
	};
	const files: FileSpec[] = [
		{
			path: 'package.json',
			content: `${packageJson(manifest, resolvedOptions)}\n`,
		},
		{
			path: '.env.example',
			content: envExample(manifest),
		},
		{
			path: 'README.md',
			content: generatedReadme(manifest),
		},
		{
			path: CONFIG_FILE,
			content: projectConfig(manifest),
		},
		{
			path: `src/index.${extension}`,
			content: renderEntryFile(manifest),
		},
		{
			path: `src/config/env.${extension}`,
			content: envConfig(manifest.language),
		},
	];

	if (manifest.features.git) {
		files.push({
			path: '.gitignore',
			content: `node_modules\ndist\n.env\n`,
		});
	}

	files.push(...renderInitialHandlerFiles(manifest));

	const tsConfigContent = tsconfig(manifest);
	if (tsConfigContent) {
		files.push({
			path: 'tsconfig.json',
			content: `${tsConfigContent}\n`,
		});
	}

	const eslintConfigContent = eslintConfig(manifest);
	if (eslintConfigContent) {
		files.push({
			path: 'eslint.config.js',
			content: eslintConfigContent,
		});
	}

	const prettierConfigContent = prettierConfig(manifest);
	if (prettierConfigContent) {
		files.push({
			path: '.prettierrc.json',
			content: `${prettierConfigContent}\n`,
		});
	}

	const biomeConfigContent = biomeConfig(manifest);
	if (biomeConfigContent) {
		files.push({
			path: 'biome.json',
			content: `${biomeConfigContent}\n`,
		});
	}

	files.push(...renderStarterRuntimeFiles(manifest));
	files.push(...databaseFiles(manifest));
	files.push(...prismaFiles(manifest));
	files.push(...dockerFiles(manifest));
	files.push(...ciFiles(manifest));

	return files;
}
